import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { manageAgent404 } from '../src/agent-404.js';

let dir: string;
let warnings: string[];
let recommendations: string[];

const warn = (message: string): void => {
  warnings.push(message);
};
const recommend = (message: string): void => {
  recommendations.push(message);
};

beforeEach(() => {
  dir = mkdtempSync(join(tmpdir(), 'ax-agent-404-'));
  warnings = [];
  recommendations = [];
});

afterEach(() => {
  rmSync(dir, { recursive: true, force: true });
});

function write(relPath: string, contents: string): void {
  const full = join(dir, relPath);
  mkdirSync(join(full, '..'), { recursive: true });
  writeFileSync(full, contents, 'utf8');
}

function run(overrides: Partial<Parameters<typeof manageAgent404>[0]> = {}) {
  return manageAgent404({
    cwd: dir,
    scaffold: false,
    basePath: '',
    llmsTxtFound: false,
    sitemapFound: false,
    warn,
    recommend,
    ...overrides,
  });
}

describe('manageAgent404 — detect-and-recommend', () => {
  it('does nothing without an app dir', () => {
    const result = run();
    expect(result).toEqual({ notFoundPresent: false, agentAware: false });
    expect(recommendations).toEqual([]);
  });

  it('recommends adding a not-found page when none exists', () => {
    mkdirSync(join(dir, 'app'), { recursive: true });

    const result = run();
    expect(result.notFoundPresent).toBe(false);
    expect(recommendations.join('\n')).toContain('No app/not-found.tsx found');
    expect(recommendations.join('\n')).toContain('scaffoldAgent404');
  });

  it('recommends signposts when a not-found page exists without any', () => {
    write(
      join('app', 'not-found.tsx'),
      'export default function NotFound() { return <h1>404</h1>; }',
    );

    const result = run();
    expect(result).toMatchObject({
      notFoundPresent: true,
      agentAware: false,
      source: join('app', 'not-found.tsx'),
    });
    expect(recommendations.join('\n')).toContain('point agents anywhere');
  });

  it('stays quiet when an existing not-found page already signposts agents', () => {
    write(
      join('app', 'not-found.tsx'),
      'export default function NotFound() { return <a href="/llms.txt">llms.txt</a>; }',
    );

    const result = run();
    expect(result).toMatchObject({ notFoundPresent: true, agentAware: true });
    expect(recommendations).toEqual([]);
  });
});

describe('manageAgent404 — scaffolding (opt-in)', () => {
  it('scaffolds not-found.tsx plus the data module, with current routes and links', () => {
    write('tsconfig.json', '{}');
    write(join('app', 'page.tsx'), 'export default function Page() { return null; }');
    write(join('app', 'docs', 'page.tsx'), 'export default function Page() { return null; }');
    write(
      join('app', 'blog', '[slug]', 'page.tsx'),
      'export default function Page() { return null; }',
    );

    const result = run({ scaffold: true, llmsTxtFound: true, sitemapFound: true });

    expect(result.notFoundPresent).toBe(true);
    expect(result.agentAware).toBe(true);
    expect(existsSync(join(dir, 'app', 'not-found.tsx'))).toBe(true);

    const data = readFileSync(join(dir, 'app', 'not-found-agent-data.ts'), 'utf8');
    expect(data).toContain('Generated by ax');
    // Static routes only — the dynamic [slug] route must be absent (never guessed).
    expect(data).toContain('"/docs"');
    expect(data).not.toContain('[slug]');
    // Discovery links reflect what was actually detected this run.
    expect(data).toContain('/.well-known/ai-catalog.json');
    expect(data).toContain('/llms.txt');
    expect(data).toContain('/sitemap.xml');

    expect(warnings.join('\n')).toContain('Scaffolded an agent-aware 404 page');
  });

  it('omits llms.txt / sitemap links when those artifacts are absent', () => {
    write('tsconfig.json', '{}');
    write(join('app', 'page.tsx'), 'export default function Page() { return null; }');

    run({ scaffold: true });
    const data = readFileSync(join(dir, 'app', 'not-found-agent-data.ts'), 'utf8');
    expect(data).toContain('/.well-known/ai-catalog.json');
    expect(data).not.toContain('/llms.txt');
    expect(data).not.toContain('/sitemap.xml');
  });

  it('prefixes discovery links with basePath', () => {
    write('tsconfig.json', '{}');
    write(join('app', 'page.tsx'), 'export default function Page() { return null; }');

    run({ scaffold: true, basePath: '/store', llmsTxtFound: true });
    const data = readFileSync(join(dir, 'app', 'not-found-agent-data.ts'), 'utf8');
    expect(data).toContain('/store/.well-known/ai-catalog.json');
    expect(data).toContain('/store/llms.txt');
  });

  it('never overwrites an existing not-found page, but keeps a scaffolded one fresh', () => {
    write('tsconfig.json', '{}');
    write(join('app', 'page.tsx'), 'export default function Page() { return null; }');

    // First run scaffolds; a second run must not rewrite not-found.tsx but must regenerate data.
    run({ scaffold: true });
    const scaffolded = readFileSync(join(dir, 'app', 'not-found.tsx'), 'utf8');
    write(join('app', 'pricing', 'page.tsx'), 'export default function Page() { return null; }');

    const result = run({ scaffold: true });
    expect(readFileSync(join(dir, 'app', 'not-found.tsx'), 'utf8')).toBe(scaffolded);
    expect(result.scaffoldedPath).toBeUndefined();
    const data = readFileSync(join(dir, 'app', 'not-found-agent-data.ts'), 'utf8');
    expect(data).toContain('"/pricing"');
  });

  it('scaffolds .jsx and a .js data module for a JavaScript project', () => {
    write(join('app', 'page.jsx'), 'export default function Page() { return null; }');

    run({ scaffold: true });
    expect(existsSync(join(dir, 'app', 'not-found.jsx'))).toBe(true);
    expect(existsSync(join(dir, 'app', 'not-found-agent-data.js'))).toBe(true);
  });

  it('does not regenerate the data module for a hand-written page that never imports it', () => {
    write('tsconfig.json', '{}');
    write(
      join('app', 'not-found.tsx'),
      'export default function NotFound() { return <a href="/llms.txt">llms.txt</a>; }',
    );

    run({ scaffold: true });
    expect(existsSync(join(dir, 'app', 'not-found-agent-data.ts'))).toBe(false);
  });

  it('never throws — a scan is best-effort', () => {
    expect(() => run({ scaffold: true })).not.toThrow();
  });
});

describe('manageAgent404 — Pages Router', () => {
  it('does nothing without an app or pages dir', () => {
    expect(run()).toEqual({ notFoundPresent: false, agentAware: false });
  });

  it('detects an existing pages/404.tsx and recommends signposts when it has none', () => {
    write(join('pages', '404.tsx'), 'export default function NotFound() { return <h1>404</h1>; }');

    const result = run();
    expect(result).toMatchObject({
      notFoundPresent: true,
      agentAware: false,
      source: join('pages', '404.tsx'),
    });
    expect(recommendations.join('\n')).toContain('point agents anywhere');
  });

  it('recommends the pages/404 convention path when none exists', () => {
    mkdirSync(join(dir, 'pages'), { recursive: true });

    const result = run();
    expect(result.notFoundPresent).toBe(false);
    expect(recommendations.join('\n')).toContain('No pages/404.tsx found');
  });

  it('scaffolds pages/404.tsx plus a data module whose routes come from the pages dir', () => {
    write('tsconfig.json', '{}');
    write(join('pages', 'index.tsx'), 'export default function H() { return null; }');
    write(join('pages', 'about.tsx'), 'export default function A() { return null; }');

    const result = run({ scaffold: true });
    expect(result.notFoundPresent).toBe(true);
    expect(existsSync(join(dir, 'pages', '404.tsx'))).toBe(true);

    const dataModule = readFileSync(join(dir, 'pages', 'not-found-agent-data.ts'), 'utf8');
    expect(dataModule).toContain('"/about"');
    expect(dataModule).toContain('"/"');
  });

  it('prefers the App Router when both routers are present', () => {
    write('tsconfig.json', '{}');
    mkdirSync(join(dir, 'app'), { recursive: true });
    mkdirSync(join(dir, 'pages'), { recursive: true });

    run({ scaffold: true });
    expect(existsSync(join(dir, 'app', 'not-found.tsx'))).toBe(true);
    expect(existsSync(join(dir, 'pages', '404.tsx'))).toBe(false);
  });
});
